### ISSUE TITLE
Finish Strong Equivalence proof for Dyck Grammar/Traces

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/grammars-and-semantic-actions#12]

**Comment by maxsnew** [comment]
Who's working on this, @stschaef or me?

**Comment by stschaef** [comment]
Me

**Comment by maxsnew** [comment]
This will be doable after https://github.com/maxsnew/grammars-and-semantic-actions/issues/27

**Comment by maxsnew** [comment]
Implemented in https://github.com/maxsnew/grammars-and-semantic-actions/pull/28
