### ISSUE TITLE
NFA Parser

### ISSUE THREAD

**Issue by stschaef** [maxsnew/grammars-and-semantic-actions#7]
Build a lazy parser for NFAs

Some proposed strategies

1. Defined via a fold that carries a finite subset of states, and then produces a squashed parse
2. Some fold involving the search monad
3. Producing a lazy multiset. Index the cardinalities by states `f : ⟨ Q ⟩ → subcountable_cardinals`, and then index the return type as a linear pi over a linear sigma over the `f q`'s --- something roughly like `LinΣ[ n ∈ f q ] LinΠ[ m ∈ n ] Parse q`. That is, for a state `q` we assign a nonlinear cardinality `f q` and we must be able to produce `f q` many parses from state `q` to some accepting state.

**Comment by maxsnew** [comment]
I think one way to make the `Search` monad easier to use would be to add a case for non-deterministic choice directly:
```
record Search (g : Grammar ℓG) (w : String) : Type ℓG where
  coinductive
  field
    viewSearch :
      -- found one thing
      (g 
      -- found nothing
      ⊕ ⊤-grammar {ℓ-zero}
      -- split into two parallel searches
      ⊕ Search g & Search g
      -- "thinking"
      ⊕ Search g) w
```
This makes it trivial to implement `append`, which is pretty annoying with the current definition.

**Comment by maxsnew** [comment]
I would try choice 2: implement a function `string ⊢ Search (LinΣ[ q ] Parse q)` as a fold.

**Comment by stschaef** [comment]
I feel silly staring at this so long, but how trivial is the `append` definition?

Any potential definition of `append` via an unfold seems like a nonstarter. Say if you unfold first, we are then building a coalgebra structure for `Search g & Search g`, and so we'd need an intermediary term `Search g & Search g ⊢ (Search g & Search g) & (Search g & Search g)` and it's not immediately clear to me what this should be. Which makes me think I'm missing something obvious

**Comment by maxsnew** [comment]
You can prove that `Search g` is isomorphic to its unfolding within the type theory using Lambek's lemma (https://ncatlab.org/nlab/show/initial+algebra+of+an+endofunctor#LambeksTheorem). Alternatively since it's admissible anyway you can just define it in Agda using the constructor.

**Comment by stschaef** [comment]
I think I'm picking up what you're saying and have implemented an attempt at it. Modulo this implementation being right, we are then one lemma away from the desired NFA parser.  

All pushed on the `search-monad` branch in `NFA.Parser`. The remainder should amount to some lemma showing that if you have a linear pi that (that's over a finite type `A`) in the context, and have a decidable predicate on `A`, then you should get a term to a `Search` type that filters out the ones that satisfy this predicate

**Comment by maxsnew** [comment]
You're missing the epsilon transitions in the nil case.

**Comment by maxsnew** [comment]
I think our current approach to this is to get a weak equivalence with the determinized DFA instead?

**Comment by maxsnew** [comment]
We gave up on the coinductive approach because coinduction stinks, but we implemented an NFA DFA equivalence so that does get us an NFA parser right now
