### ISSUE TITLE
Parser Combinators

### ISSUE THREAD

**Issue by stschaef** [maxsnew/grammars-and-semantic-actions#8]
Reimplement a barebones parser combinator library a la Parsec

Seems that to accomplish this goal, parsers should be typed as
```
Parser : Grammar ℓg → Type ℓg
Parser g = string-grammar ⊢ Search (g ⊗ string-grammar)
```

And then some combinators should be implemented atop the monadic structure on parsers. Such as sequencing and alternation

**Comment by maxsnew** [comment]
Might work but coinduction is a PITA
